name: squash_merge_to_prod
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
jobs:
  squash_merge_to_prod:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # only run if PR merged (subset of 'closed')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: Configure Git
      run: |
        git config user.name "Jai Bhagat"
        git config user.email "jkbhagatio@gmail.com"
    - name: Merge and squash to prod
      run: |
        git checkout prod
        # Get the latest commit message from the 'main' branch
        COMMIT_MSG=$(git log main -1 --pretty=format:%s)
        git merge --squash -X theirs main
        git commit -m "$COMMIT_MSG"
        git push origin prod

# a commit
# a commit
# feature commit 1
# feature commit 2
# feature commit 3
# feature commit 4