name: squash_merge_to_prod
on:
  push:
    branches: [ main ]
jobs:
  squash_merge_to_prod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: Configure Git
      run: |
        git config user.name "Jai Bhagat"
        git config user.email "jkbhagatio@gmail.com"
    - name: Merge and squash to prod
      run: |
        git checkout prod
        # Get the latest commit message from the 'main' branch
        COMMIT_MSG=$(git log main -1 --pretty=format:%s)
        git merge --squash main
        git commit -m "$COMMIT_MSG"
        git push origin prod

# a commit
# a commit
# feature commit 1